spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_with_kotlin
    username: root
    password: Sql@4321
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8300
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
jwt:
  secret:
    key: c3d56c5f9bf484b916adc08f9062a0cdf20b9544df6c073da2ab5466336673fe