spring:
  application:
    name: address-service
  datasource:
    url: jdbc:mysql://localhost:3306/spring_boot_with_kotlin
    username: root
    password: Sql@4321
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8200
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
