spring:
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      routes:
#        - id: address-service
#          uri: http://localhost:8200
#          predicates:
#            - Path= /address/**
server:
  port: 8765
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
jwt:
  secret:
    key: c3d56c5f9bf484b916adc08f9062a0cdf20b9544df6c073da2ab5466336673fe
